# Unchangables
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


safe: true

# Forced Plugins:
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  
whitelist:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  

highlighter: rouge
markdown: kramdown


kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true
    
    
socials:
  - github: "https://github.com/multarix"
  - steam: "https://steamcommunity.com/id/multarix"
  
  - twitter: "https://twitter.com/multarix"
  - youtube: "https://youtube.com/multarix_"

  - reddit: "https://reddit.com/u/multarix"
  - twitch: "https://twitch.tv/multarix"
  - instagram: "https://instagram.com/your-instagram"
  - facebook: "https://facebook.com/your-facebook"
  - snapchat: "https://snapchat.com/add/your-snapchat"

  


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      siteName: "Multarix Projects"
      

incremental: false
livereload: true
url: multarix.com

exclude:
  - readme.md