import { BinaryOctalObject, HexObject, SubScript } from "./types/interfaces";
declare const subScript: SubScript;
declare const hexObject: HexObject;
declare const binaryHexObject: {
    "0000": string;
    "0001": string;
    "0010": string;
    "0011": string;
    "0100": string;
    "0101": string;
    "0110": string;
    "0111": string;
    "1000": string;
    "1001": string;
    "1010": string;
    "1011": string;
    "1100": string;
    "1101": string;
    "1110": string;
    "1111": string;
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    A: string;
    B: string;
    C: string;
    D: string;
    E: string;
    F: string;
};
declare const binaryOctalObject: BinaryOctalObject;
export { binaryHexObject, binaryOctalObject, hexObject, subScript };
